name: "Build cache"
on: [pull_request, push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: synthxacxe
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix-build shell.nix
    - run: nix-shell --run "echo OK"
